[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.24.0"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.3.2"

[[override]]
  name = "github.com/golang/protobuf"
  version = "1.3.2"