// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc-hello/v1/grpc-hello.proto

/*
Package grpc_hello is a generated protocol buffer package.

It is generated from these files:
	grpc-hello/v1/grpc-hello.proto

It has these top-level messages:
	SayHelloRequest
	SayHelloResponse
*/
package grpc_hello

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SayHelloRequest struct {
	Neme string `protobuf:"bytes,1,opt,name=neme" json:"neme,omitempty"`
}

func (m *SayHelloRequest) Reset()                    { *m = SayHelloRequest{} }
func (m *SayHelloRequest) String() string            { return proto.CompactTextString(m) }
func (*SayHelloRequest) ProtoMessage()               {}
func (*SayHelloRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SayHelloRequest) GetNeme() string {
	if m != nil {
		return m.Neme
	}
	return ""
}

type SayHelloResponse struct {
	Greeting string `protobuf:"bytes,1,opt,name=greeting" json:"greeting,omitempty"`
}

func (m *SayHelloResponse) Reset()                    { *m = SayHelloResponse{} }
func (m *SayHelloResponse) String() string            { return proto.CompactTextString(m) }
func (*SayHelloResponse) ProtoMessage()               {}
func (*SayHelloResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SayHelloResponse) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

func init() {
	proto.RegisterType((*SayHelloRequest)(nil), "ellulpatrick.hello.v1.SayHelloRequest")
	proto.RegisterType((*SayHelloResponse)(nil), "ellulpatrick.hello.v1.SayHelloResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for HelloService service

type HelloServiceClient interface {
	SayHello(ctx context.Context, in *SayHelloRequest, opts ...grpc.CallOption) (*SayHelloResponse, error)
}

type helloServiceClient struct {
	cc *grpc.ClientConn
}

func NewHelloServiceClient(cc *grpc.ClientConn) HelloServiceClient {
	return &helloServiceClient{cc}
}

func (c *helloServiceClient) SayHello(ctx context.Context, in *SayHelloRequest, opts ...grpc.CallOption) (*SayHelloResponse, error) {
	out := new(SayHelloResponse)
	err := grpc.Invoke(ctx, "/ellulpatrick.hello.v1.HelloService/SayHello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for HelloService service

type HelloServiceServer interface {
	SayHello(context.Context, *SayHelloRequest) (*SayHelloResponse, error)
}

func RegisterHelloServiceServer(s *grpc.Server, srv HelloServiceServer) {
	s.RegisterService(&_HelloService_serviceDesc, srv)
}

func _HelloService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SayHelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ellulpatrick.hello.v1.HelloService/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServiceServer).SayHello(ctx, req.(*SayHelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HelloService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ellulpatrick.hello.v1.HelloService",
	HandlerType: (*HelloServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _HelloService_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc-hello/v1/grpc-hello.proto",
}

func init() { proto.RegisterFile("grpc-hello/v1/grpc-hello.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4b, 0x2f, 0x2a, 0x48,
	0xd6, 0xcd, 0x48, 0xcd, 0xc9, 0xc9, 0xd7, 0x2f, 0x33, 0xd4, 0x47, 0xf0, 0xf4, 0x0a, 0x8a, 0xf2,
	0x4b, 0xf2, 0x85, 0x44, 0x53, 0x73, 0x72, 0x4a, 0x73, 0x0a, 0x12, 0x4b, 0x8a, 0x32, 0x93, 0xb3,
	0xf5, 0x20, 0x32, 0x65, 0x86, 0x4a, 0xaa, 0x5c, 0xfc, 0xc1, 0x89, 0x95, 0x1e, 0x20, 0x6e, 0x50,
	0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89, 0x90, 0x10, 0x17, 0x4b, 0x5e, 0x6a, 0x6e, 0xaa, 0x04, 0xa3,
	0x02, 0xa3, 0x06, 0x67, 0x10, 0x98, 0xad, 0xa4, 0xc7, 0x25, 0x80, 0x50, 0x56, 0x5c, 0x90, 0x9f,
	0x57, 0x9c, 0x2a, 0x24, 0xc5, 0xc5, 0x91, 0x5e, 0x94, 0x9a, 0x5a, 0x92, 0x99, 0x97, 0x0e, 0x55,
	0x0b, 0xe7, 0x1b, 0x65, 0x73, 0xf1, 0x80, 0x15, 0x07, 0xa7, 0x16, 0x95, 0x65, 0x26, 0xa7, 0x0a,
	0x45, 0x73, 0x71, 0xc0, 0xf4, 0x0b, 0xa9, 0xe9, 0x61, 0x75, 0x8a, 0x1e, 0x9a, 0x3b, 0xa4, 0xd4,
	0x09, 0xaa, 0x83, 0x38, 0xc4, 0x49, 0x2a, 0x4a, 0x02, 0xc5, 0xf3, 0xd6, 0x08, 0x5e, 0x12, 0x1b,
	0xd8, 0xf7, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb5, 0x77, 0x99, 0xcb, 0x1f, 0x01, 0x00,
	0x00,
}
